Repository Viindoo/customer-s5t-odoo, pull requests merged in 2024-07, with the labels that each got.

#12 [IMP] portal: validation portal
  addons/portal/controllers/portal.py
  addons/portal/i18n/portal.pot
  addons/portal/i18n/vi.po
Labels: :rocket: Running

#13 [IMP] http: remove debug stacktrace in response
  odoo/http.py
Labels: :rocket: Queue

#14 [IMP] mail: restrict upload file type using whitelist instead of blacklist
  addons/mail/controllers/discuss.py
Labels: :rocket: Building

#16 [IMP] base: format read of password for res.users
  odoo/addons/base/models/res_users.py
Labels: :rocket: Building
